name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # disabled for now
        raku-version:
          - 'latest'
          - '2020.11'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Upgrade zef
        run: zef upgrade --/test zef
      - name: Install Dependencies
        run: zef install --/test --deps-only .
      - name: Install Development Dependencies
        run: zef install --/test App::Prove6 File::Temp Distribution::Builder::MakeFromJSON
      - name: Run Tests
        run: prove6 -I.,lib t xt
